/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BackofficeLoginRouteImport } from './routes/backoffice-login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedUnlockedRouteImport } from './routes/_authenticated/_unlocked'
import { Route as AuthenticatedCoachIndexRouteImport } from './routes/_authenticated/coach/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedCoachEntrepreneurIdRouteImport } from './routes/_authenticated/coach/$entrepreneurId'
import { Route as AuthenticatedAdminParametragesRouteImport } from './routes/_authenticated/admin/parametrages'
import { Route as AuthenticatedUnlockedVoiceHistoryRouteImport } from './routes/_authenticated/_unlocked/voice-history'
import { Route as AuthenticatedUnlockedVoiceRouteImport } from './routes/_authenticated/_unlocked/voice'
import { Route as AuthenticatedUnlockedTransactionsRouteImport } from './routes/_authenticated/_unlocked/transactions'
import { Route as AuthenticatedUnlockedSettingsRouteImport } from './routes/_authenticated/_unlocked/settings'
import { Route as AuthenticatedUnlockedReceivablesRouteImport } from './routes/_authenticated/_unlocked/receivables'
import { Route as AuthenticatedUnlockedAppRouteImport } from './routes/_authenticated/_unlocked/app'
import { Route as AuthenticatedUnlockedSettingsIndexRouteImport } from './routes/_authenticated/_unlocked/settings/index'
import { Route as AuthenticatedUnlockedSettingsVendeursRouteImport } from './routes/_authenticated/_unlocked/settings/vendeurs'
import { Route as AuthenticatedUnlockedSettingsTontineRouteImport } from './routes/_authenticated/_unlocked/settings/tontine'
import { Route as AuthenticatedUnlockedSettingsStatsRouteImport } from './routes/_authenticated/_unlocked/settings/stats'
import { Route as AuthenticatedUnlockedSettingsSimulationRouteImport } from './routes/_authenticated/_unlocked/settings/simulation'
import { Route as AuthenticatedUnlockedSettingsSecurityRouteImport } from './routes/_authenticated/_unlocked/settings/security'
import { Route as AuthenticatedUnlockedSettingsProfileRouteImport } from './routes/_authenticated/_unlocked/settings/profile'
import { Route as AuthenticatedUnlockedSettingsPretsRouteImport } from './routes/_authenticated/_unlocked/settings/prets'
import { Route as AuthenticatedUnlockedSettingsPointsDeVenteRouteImport } from './routes/_authenticated/_unlocked/settings/points-de-vente'
import { Route as AuthenticatedUnlockedSettingsLanguageRouteImport } from './routes/_authenticated/_unlocked/settings/language'
import { Route as AuthenticatedUnlockedSettingsContactsRouteImport } from './routes/_authenticated/_unlocked/settings/contacts'
import { Route as AuthenticatedUnlockedSettingsActivitiesRouteImport } from './routes/_authenticated/_unlocked/settings/activities'
import { Route as AuthenticatedUnlockedOnboardingTourRouteImport } from './routes/_authenticated/_unlocked/onboarding/tour'
import { Route as AuthenticatedUnlockedOnboardingProfileRouteImport } from './routes/_authenticated/_unlocked/onboarding/profile'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeLoginRoute = BackofficeLoginRouteImport.update({
  id: '/backoffice-login',
  path: '/backoffice-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnlockedRoute = AuthenticatedUnlockedRouteImport.update({
  id: '/_unlocked',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoachIndexRoute = AuthenticatedCoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCoachRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedCoachEntrepreneurIdRoute =
  AuthenticatedCoachEntrepreneurIdRouteImport.update({
    id: '/$entrepreneurId',
    path: '/$entrepreneurId',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedAdminParametragesRoute =
  AuthenticatedAdminParametragesRouteImport.update({
    id: '/parametrages',
    path: '/parametrages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedUnlockedVoiceHistoryRoute =
  AuthenticatedUnlockedVoiceHistoryRouteImport.update({
    id: '/voice-history',
    path: '/voice-history',
    getParentRoute: () => AuthenticatedUnlockedRoute,
  } as any)
const AuthenticatedUnlockedVoiceRoute =
  AuthenticatedUnlockedVoiceRouteImport.update({
    id: '/voice',
    path: '/voice',
    getParentRoute: () => AuthenticatedUnlockedRoute,
  } as any)
const AuthenticatedUnlockedTransactionsRoute =
  AuthenticatedUnlockedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedUnlockedRoute,
  } as any)
const AuthenticatedUnlockedSettingsRoute =
  AuthenticatedUnlockedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedUnlockedRoute,
  } as any)
const AuthenticatedUnlockedReceivablesRoute =
  AuthenticatedUnlockedReceivablesRouteImport.update({
    id: '/receivables',
    path: '/receivables',
    getParentRoute: () => AuthenticatedUnlockedRoute,
  } as any)
const AuthenticatedUnlockedAppRoute =
  AuthenticatedUnlockedAppRouteImport.update({
    id: '/app',
    path: '/app',
    getParentRoute: () => AuthenticatedUnlockedRoute,
  } as any)
const AuthenticatedUnlockedSettingsIndexRoute =
  AuthenticatedUnlockedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUnlockedSettingsRoute,
  } as any)
const AuthenticatedUnlockedSettingsVendeursRoute =
  AuthenticatedUnlockedSettingsVendeursRouteImport.update({
    id: '/vendeurs',
    path: '/vendeurs',
    getParentRoute: () => AuthenticatedUnlockedSettingsRoute,
  } as any)
const AuthenticatedUnlockedSettingsTontineRoute =
  AuthenticatedUnlockedSettingsTontineRouteImport.update({
    id: '/tontine',
    path: '/tontine',
    getParentRoute: () => AuthenticatedUnlockedSettingsRoute,
  } as any)
const AuthenticatedUnlockedSettingsStatsRoute =
  AuthenticatedUnlockedSettingsStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedUnlockedSettingsRoute,
  } as any)
const AuthenticatedUnlockedSettingsSimulationRoute =
  AuthenticatedUnlockedSettingsSimulationRouteImport.update({
    id: '/simulation',
    path: '/simulation',
    getParentRoute: () => AuthenticatedUnlockedSettingsRoute,
  } as any)
const AuthenticatedUnlockedSettingsSecurityRoute =
  AuthenticatedUnlockedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedUnlockedSettingsRoute,
  } as any)
const AuthenticatedUnlockedSettingsProfileRoute =
  AuthenticatedUnlockedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedUnlockedSettingsRoute,
  } as any)
const AuthenticatedUnlockedSettingsPretsRoute =
  AuthenticatedUnlockedSettingsPretsRouteImport.update({
    id: '/prets',
    path: '/prets',
    getParentRoute: () => AuthenticatedUnlockedSettingsRoute,
  } as any)
const AuthenticatedUnlockedSettingsPointsDeVenteRoute =
  AuthenticatedUnlockedSettingsPointsDeVenteRouteImport.update({
    id: '/points-de-vente',
    path: '/points-de-vente',
    getParentRoute: () => AuthenticatedUnlockedSettingsRoute,
  } as any)
const AuthenticatedUnlockedSettingsLanguageRoute =
  AuthenticatedUnlockedSettingsLanguageRouteImport.update({
    id: '/language',
    path: '/language',
    getParentRoute: () => AuthenticatedUnlockedSettingsRoute,
  } as any)
const AuthenticatedUnlockedSettingsContactsRoute =
  AuthenticatedUnlockedSettingsContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedUnlockedSettingsRoute,
  } as any)
const AuthenticatedUnlockedSettingsActivitiesRoute =
  AuthenticatedUnlockedSettingsActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => AuthenticatedUnlockedSettingsRoute,
  } as any)
const AuthenticatedUnlockedOnboardingTourRoute =
  AuthenticatedUnlockedOnboardingTourRouteImport.update({
    id: '/onboarding/tour',
    path: '/onboarding/tour',
    getParentRoute: () => AuthenticatedUnlockedRoute,
  } as any)
const AuthenticatedUnlockedOnboardingProfileRoute =
  AuthenticatedUnlockedOnboardingProfileRouteImport.update({
    id: '/onboarding/profile',
    path: '/onboarding/profile',
    getParentRoute: () => AuthenticatedUnlockedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backoffice-login': typeof BackofficeLoginRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/coach': typeof AuthenticatedCoachRouteWithChildren
  '/app': typeof AuthenticatedUnlockedAppRoute
  '/receivables': typeof AuthenticatedUnlockedReceivablesRoute
  '/settings': typeof AuthenticatedUnlockedSettingsRouteWithChildren
  '/transactions': typeof AuthenticatedUnlockedTransactionsRoute
  '/voice': typeof AuthenticatedUnlockedVoiceRoute
  '/voice-history': typeof AuthenticatedUnlockedVoiceHistoryRoute
  '/admin/parametrages': typeof AuthenticatedAdminParametragesRoute
  '/coach/$entrepreneurId': typeof AuthenticatedCoachEntrepreneurIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/coach/': typeof AuthenticatedCoachIndexRoute
  '/onboarding/profile': typeof AuthenticatedUnlockedOnboardingProfileRoute
  '/onboarding/tour': typeof AuthenticatedUnlockedOnboardingTourRoute
  '/settings/activities': typeof AuthenticatedUnlockedSettingsActivitiesRoute
  '/settings/contacts': typeof AuthenticatedUnlockedSettingsContactsRoute
  '/settings/language': typeof AuthenticatedUnlockedSettingsLanguageRoute
  '/settings/points-de-vente': typeof AuthenticatedUnlockedSettingsPointsDeVenteRoute
  '/settings/prets': typeof AuthenticatedUnlockedSettingsPretsRoute
  '/settings/profile': typeof AuthenticatedUnlockedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedUnlockedSettingsSecurityRoute
  '/settings/simulation': typeof AuthenticatedUnlockedSettingsSimulationRoute
  '/settings/stats': typeof AuthenticatedUnlockedSettingsStatsRoute
  '/settings/tontine': typeof AuthenticatedUnlockedSettingsTontineRoute
  '/settings/vendeurs': typeof AuthenticatedUnlockedSettingsVendeursRoute
  '/settings/': typeof AuthenticatedUnlockedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backoffice-login': typeof BackofficeLoginRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedUnlockedAppRoute
  '/receivables': typeof AuthenticatedUnlockedReceivablesRoute
  '/transactions': typeof AuthenticatedUnlockedTransactionsRoute
  '/voice': typeof AuthenticatedUnlockedVoiceRoute
  '/voice-history': typeof AuthenticatedUnlockedVoiceHistoryRoute
  '/admin/parametrages': typeof AuthenticatedAdminParametragesRoute
  '/coach/$entrepreneurId': typeof AuthenticatedCoachEntrepreneurIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/coach': typeof AuthenticatedCoachIndexRoute
  '/onboarding/profile': typeof AuthenticatedUnlockedOnboardingProfileRoute
  '/onboarding/tour': typeof AuthenticatedUnlockedOnboardingTourRoute
  '/settings/activities': typeof AuthenticatedUnlockedSettingsActivitiesRoute
  '/settings/contacts': typeof AuthenticatedUnlockedSettingsContactsRoute
  '/settings/language': typeof AuthenticatedUnlockedSettingsLanguageRoute
  '/settings/points-de-vente': typeof AuthenticatedUnlockedSettingsPointsDeVenteRoute
  '/settings/prets': typeof AuthenticatedUnlockedSettingsPretsRoute
  '/settings/profile': typeof AuthenticatedUnlockedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedUnlockedSettingsSecurityRoute
  '/settings/simulation': typeof AuthenticatedUnlockedSettingsSimulationRoute
  '/settings/stats': typeof AuthenticatedUnlockedSettingsStatsRoute
  '/settings/tontine': typeof AuthenticatedUnlockedSettingsTontineRoute
  '/settings/vendeurs': typeof AuthenticatedUnlockedSettingsVendeursRoute
  '/settings': typeof AuthenticatedUnlockedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/backoffice-login': typeof BackofficeLoginRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_unlocked': typeof AuthenticatedUnlockedRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/coach': typeof AuthenticatedCoachRouteWithChildren
  '/_authenticated/_unlocked/app': typeof AuthenticatedUnlockedAppRoute
  '/_authenticated/_unlocked/receivables': typeof AuthenticatedUnlockedReceivablesRoute
  '/_authenticated/_unlocked/settings': typeof AuthenticatedUnlockedSettingsRouteWithChildren
  '/_authenticated/_unlocked/transactions': typeof AuthenticatedUnlockedTransactionsRoute
  '/_authenticated/_unlocked/voice': typeof AuthenticatedUnlockedVoiceRoute
  '/_authenticated/_unlocked/voice-history': typeof AuthenticatedUnlockedVoiceHistoryRoute
  '/_authenticated/admin/parametrages': typeof AuthenticatedAdminParametragesRoute
  '/_authenticated/coach/$entrepreneurId': typeof AuthenticatedCoachEntrepreneurIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/coach/': typeof AuthenticatedCoachIndexRoute
  '/_authenticated/_unlocked/onboarding/profile': typeof AuthenticatedUnlockedOnboardingProfileRoute
  '/_authenticated/_unlocked/onboarding/tour': typeof AuthenticatedUnlockedOnboardingTourRoute
  '/_authenticated/_unlocked/settings/activities': typeof AuthenticatedUnlockedSettingsActivitiesRoute
  '/_authenticated/_unlocked/settings/contacts': typeof AuthenticatedUnlockedSettingsContactsRoute
  '/_authenticated/_unlocked/settings/language': typeof AuthenticatedUnlockedSettingsLanguageRoute
  '/_authenticated/_unlocked/settings/points-de-vente': typeof AuthenticatedUnlockedSettingsPointsDeVenteRoute
  '/_authenticated/_unlocked/settings/prets': typeof AuthenticatedUnlockedSettingsPretsRoute
  '/_authenticated/_unlocked/settings/profile': typeof AuthenticatedUnlockedSettingsProfileRoute
  '/_authenticated/_unlocked/settings/security': typeof AuthenticatedUnlockedSettingsSecurityRoute
  '/_authenticated/_unlocked/settings/simulation': typeof AuthenticatedUnlockedSettingsSimulationRoute
  '/_authenticated/_unlocked/settings/stats': typeof AuthenticatedUnlockedSettingsStatsRoute
  '/_authenticated/_unlocked/settings/tontine': typeof AuthenticatedUnlockedSettingsTontineRoute
  '/_authenticated/_unlocked/settings/vendeurs': typeof AuthenticatedUnlockedSettingsVendeursRoute
  '/_authenticated/_unlocked/settings/': typeof AuthenticatedUnlockedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backoffice-login'
    | '/login'
    | '/signup'
    | '/admin'
    | '/coach'
    | '/app'
    | '/receivables'
    | '/settings'
    | '/transactions'
    | '/voice'
    | '/voice-history'
    | '/admin/parametrages'
    | '/coach/$entrepreneurId'
    | '/admin/'
    | '/coach/'
    | '/onboarding/profile'
    | '/onboarding/tour'
    | '/settings/activities'
    | '/settings/contacts'
    | '/settings/language'
    | '/settings/points-de-vente'
    | '/settings/prets'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/simulation'
    | '/settings/stats'
    | '/settings/tontine'
    | '/settings/vendeurs'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backoffice-login'
    | '/login'
    | '/signup'
    | '/app'
    | '/receivables'
    | '/transactions'
    | '/voice'
    | '/voice-history'
    | '/admin/parametrages'
    | '/coach/$entrepreneurId'
    | '/admin'
    | '/coach'
    | '/onboarding/profile'
    | '/onboarding/tour'
    | '/settings/activities'
    | '/settings/contacts'
    | '/settings/language'
    | '/settings/points-de-vente'
    | '/settings/prets'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/simulation'
    | '/settings/stats'
    | '/settings/tontine'
    | '/settings/vendeurs'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/backoffice-login'
    | '/login'
    | '/signup'
    | '/_authenticated/_unlocked'
    | '/_authenticated/admin'
    | '/_authenticated/coach'
    | '/_authenticated/_unlocked/app'
    | '/_authenticated/_unlocked/receivables'
    | '/_authenticated/_unlocked/settings'
    | '/_authenticated/_unlocked/transactions'
    | '/_authenticated/_unlocked/voice'
    | '/_authenticated/_unlocked/voice-history'
    | '/_authenticated/admin/parametrages'
    | '/_authenticated/coach/$entrepreneurId'
    | '/_authenticated/admin/'
    | '/_authenticated/coach/'
    | '/_authenticated/_unlocked/onboarding/profile'
    | '/_authenticated/_unlocked/onboarding/tour'
    | '/_authenticated/_unlocked/settings/activities'
    | '/_authenticated/_unlocked/settings/contacts'
    | '/_authenticated/_unlocked/settings/language'
    | '/_authenticated/_unlocked/settings/points-de-vente'
    | '/_authenticated/_unlocked/settings/prets'
    | '/_authenticated/_unlocked/settings/profile'
    | '/_authenticated/_unlocked/settings/security'
    | '/_authenticated/_unlocked/settings/simulation'
    | '/_authenticated/_unlocked/settings/stats'
    | '/_authenticated/_unlocked/settings/tontine'
    | '/_authenticated/_unlocked/settings/vendeurs'
    | '/_authenticated/_unlocked/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BackofficeLoginRoute: typeof BackofficeLoginRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice-login': {
      id: '/backoffice-login'
      path: '/backoffice-login'
      fullPath: '/backoffice-login'
      preLoaderRoute: typeof BackofficeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_unlocked': {
      id: '/_authenticated/_unlocked'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedUnlockedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach/': {
      id: '/_authenticated/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthenticatedCoachIndexRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/coach/$entrepreneurId': {
      id: '/_authenticated/coach/$entrepreneurId'
      path: '/$entrepreneurId'
      fullPath: '/coach/$entrepreneurId'
      preLoaderRoute: typeof AuthenticatedCoachEntrepreneurIdRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/admin/parametrages': {
      id: '/_authenticated/admin/parametrages'
      path: '/parametrages'
      fullPath: '/admin/parametrages'
      preLoaderRoute: typeof AuthenticatedAdminParametragesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_unlocked/voice-history': {
      id: '/_authenticated/_unlocked/voice-history'
      path: '/voice-history'
      fullPath: '/voice-history'
      preLoaderRoute: typeof AuthenticatedUnlockedVoiceHistoryRouteImport
      parentRoute: typeof AuthenticatedUnlockedRoute
    }
    '/_authenticated/_unlocked/voice': {
      id: '/_authenticated/_unlocked/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AuthenticatedUnlockedVoiceRouteImport
      parentRoute: typeof AuthenticatedUnlockedRoute
    }
    '/_authenticated/_unlocked/transactions': {
      id: '/_authenticated/_unlocked/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedUnlockedTransactionsRouteImport
      parentRoute: typeof AuthenticatedUnlockedRoute
    }
    '/_authenticated/_unlocked/settings': {
      id: '/_authenticated/_unlocked/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsRouteImport
      parentRoute: typeof AuthenticatedUnlockedRoute
    }
    '/_authenticated/_unlocked/receivables': {
      id: '/_authenticated/_unlocked/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof AuthenticatedUnlockedReceivablesRouteImport
      parentRoute: typeof AuthenticatedUnlockedRoute
    }
    '/_authenticated/_unlocked/app': {
      id: '/_authenticated/_unlocked/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedUnlockedAppRouteImport
      parentRoute: typeof AuthenticatedUnlockedRoute
    }
    '/_authenticated/_unlocked/settings/': {
      id: '/_authenticated/_unlocked/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedUnlockedSettingsRoute
    }
    '/_authenticated/_unlocked/settings/vendeurs': {
      id: '/_authenticated/_unlocked/settings/vendeurs'
      path: '/vendeurs'
      fullPath: '/settings/vendeurs'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsVendeursRouteImport
      parentRoute: typeof AuthenticatedUnlockedSettingsRoute
    }
    '/_authenticated/_unlocked/settings/tontine': {
      id: '/_authenticated/_unlocked/settings/tontine'
      path: '/tontine'
      fullPath: '/settings/tontine'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsTontineRouteImport
      parentRoute: typeof AuthenticatedUnlockedSettingsRoute
    }
    '/_authenticated/_unlocked/settings/stats': {
      id: '/_authenticated/_unlocked/settings/stats'
      path: '/stats'
      fullPath: '/settings/stats'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsStatsRouteImport
      parentRoute: typeof AuthenticatedUnlockedSettingsRoute
    }
    '/_authenticated/_unlocked/settings/simulation': {
      id: '/_authenticated/_unlocked/settings/simulation'
      path: '/simulation'
      fullPath: '/settings/simulation'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsSimulationRouteImport
      parentRoute: typeof AuthenticatedUnlockedSettingsRoute
    }
    '/_authenticated/_unlocked/settings/security': {
      id: '/_authenticated/_unlocked/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedUnlockedSettingsRoute
    }
    '/_authenticated/_unlocked/settings/profile': {
      id: '/_authenticated/_unlocked/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedUnlockedSettingsRoute
    }
    '/_authenticated/_unlocked/settings/prets': {
      id: '/_authenticated/_unlocked/settings/prets'
      path: '/prets'
      fullPath: '/settings/prets'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsPretsRouteImport
      parentRoute: typeof AuthenticatedUnlockedSettingsRoute
    }
    '/_authenticated/_unlocked/settings/points-de-vente': {
      id: '/_authenticated/_unlocked/settings/points-de-vente'
      path: '/points-de-vente'
      fullPath: '/settings/points-de-vente'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsPointsDeVenteRouteImport
      parentRoute: typeof AuthenticatedUnlockedSettingsRoute
    }
    '/_authenticated/_unlocked/settings/language': {
      id: '/_authenticated/_unlocked/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsLanguageRouteImport
      parentRoute: typeof AuthenticatedUnlockedSettingsRoute
    }
    '/_authenticated/_unlocked/settings/contacts': {
      id: '/_authenticated/_unlocked/settings/contacts'
      path: '/contacts'
      fullPath: '/settings/contacts'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsContactsRouteImport
      parentRoute: typeof AuthenticatedUnlockedSettingsRoute
    }
    '/_authenticated/_unlocked/settings/activities': {
      id: '/_authenticated/_unlocked/settings/activities'
      path: '/activities'
      fullPath: '/settings/activities'
      preLoaderRoute: typeof AuthenticatedUnlockedSettingsActivitiesRouteImport
      parentRoute: typeof AuthenticatedUnlockedSettingsRoute
    }
    '/_authenticated/_unlocked/onboarding/tour': {
      id: '/_authenticated/_unlocked/onboarding/tour'
      path: '/onboarding/tour'
      fullPath: '/onboarding/tour'
      preLoaderRoute: typeof AuthenticatedUnlockedOnboardingTourRouteImport
      parentRoute: typeof AuthenticatedUnlockedRoute
    }
    '/_authenticated/_unlocked/onboarding/profile': {
      id: '/_authenticated/_unlocked/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof AuthenticatedUnlockedOnboardingProfileRouteImport
      parentRoute: typeof AuthenticatedUnlockedRoute
    }
  }
}

interface AuthenticatedUnlockedSettingsRouteChildren {
  AuthenticatedUnlockedSettingsActivitiesRoute: typeof AuthenticatedUnlockedSettingsActivitiesRoute
  AuthenticatedUnlockedSettingsContactsRoute: typeof AuthenticatedUnlockedSettingsContactsRoute
  AuthenticatedUnlockedSettingsLanguageRoute: typeof AuthenticatedUnlockedSettingsLanguageRoute
  AuthenticatedUnlockedSettingsPointsDeVenteRoute: typeof AuthenticatedUnlockedSettingsPointsDeVenteRoute
  AuthenticatedUnlockedSettingsPretsRoute: typeof AuthenticatedUnlockedSettingsPretsRoute
  AuthenticatedUnlockedSettingsProfileRoute: typeof AuthenticatedUnlockedSettingsProfileRoute
  AuthenticatedUnlockedSettingsSecurityRoute: typeof AuthenticatedUnlockedSettingsSecurityRoute
  AuthenticatedUnlockedSettingsSimulationRoute: typeof AuthenticatedUnlockedSettingsSimulationRoute
  AuthenticatedUnlockedSettingsStatsRoute: typeof AuthenticatedUnlockedSettingsStatsRoute
  AuthenticatedUnlockedSettingsTontineRoute: typeof AuthenticatedUnlockedSettingsTontineRoute
  AuthenticatedUnlockedSettingsVendeursRoute: typeof AuthenticatedUnlockedSettingsVendeursRoute
  AuthenticatedUnlockedSettingsIndexRoute: typeof AuthenticatedUnlockedSettingsIndexRoute
}

const AuthenticatedUnlockedSettingsRouteChildren: AuthenticatedUnlockedSettingsRouteChildren =
  {
    AuthenticatedUnlockedSettingsActivitiesRoute:
      AuthenticatedUnlockedSettingsActivitiesRoute,
    AuthenticatedUnlockedSettingsContactsRoute:
      AuthenticatedUnlockedSettingsContactsRoute,
    AuthenticatedUnlockedSettingsLanguageRoute:
      AuthenticatedUnlockedSettingsLanguageRoute,
    AuthenticatedUnlockedSettingsPointsDeVenteRoute:
      AuthenticatedUnlockedSettingsPointsDeVenteRoute,
    AuthenticatedUnlockedSettingsPretsRoute:
      AuthenticatedUnlockedSettingsPretsRoute,
    AuthenticatedUnlockedSettingsProfileRoute:
      AuthenticatedUnlockedSettingsProfileRoute,
    AuthenticatedUnlockedSettingsSecurityRoute:
      AuthenticatedUnlockedSettingsSecurityRoute,
    AuthenticatedUnlockedSettingsSimulationRoute:
      AuthenticatedUnlockedSettingsSimulationRoute,
    AuthenticatedUnlockedSettingsStatsRoute:
      AuthenticatedUnlockedSettingsStatsRoute,
    AuthenticatedUnlockedSettingsTontineRoute:
      AuthenticatedUnlockedSettingsTontineRoute,
    AuthenticatedUnlockedSettingsVendeursRoute:
      AuthenticatedUnlockedSettingsVendeursRoute,
    AuthenticatedUnlockedSettingsIndexRoute:
      AuthenticatedUnlockedSettingsIndexRoute,
  }

const AuthenticatedUnlockedSettingsRouteWithChildren =
  AuthenticatedUnlockedSettingsRoute._addFileChildren(
    AuthenticatedUnlockedSettingsRouteChildren,
  )

interface AuthenticatedUnlockedRouteChildren {
  AuthenticatedUnlockedAppRoute: typeof AuthenticatedUnlockedAppRoute
  AuthenticatedUnlockedReceivablesRoute: typeof AuthenticatedUnlockedReceivablesRoute
  AuthenticatedUnlockedSettingsRoute: typeof AuthenticatedUnlockedSettingsRouteWithChildren
  AuthenticatedUnlockedTransactionsRoute: typeof AuthenticatedUnlockedTransactionsRoute
  AuthenticatedUnlockedVoiceRoute: typeof AuthenticatedUnlockedVoiceRoute
  AuthenticatedUnlockedVoiceHistoryRoute: typeof AuthenticatedUnlockedVoiceHistoryRoute
  AuthenticatedUnlockedOnboardingProfileRoute: typeof AuthenticatedUnlockedOnboardingProfileRoute
  AuthenticatedUnlockedOnboardingTourRoute: typeof AuthenticatedUnlockedOnboardingTourRoute
}

const AuthenticatedUnlockedRouteChildren: AuthenticatedUnlockedRouteChildren = {
  AuthenticatedUnlockedAppRoute: AuthenticatedUnlockedAppRoute,
  AuthenticatedUnlockedReceivablesRoute: AuthenticatedUnlockedReceivablesRoute,
  AuthenticatedUnlockedSettingsRoute:
    AuthenticatedUnlockedSettingsRouteWithChildren,
  AuthenticatedUnlockedTransactionsRoute:
    AuthenticatedUnlockedTransactionsRoute,
  AuthenticatedUnlockedVoiceRoute: AuthenticatedUnlockedVoiceRoute,
  AuthenticatedUnlockedVoiceHistoryRoute:
    AuthenticatedUnlockedVoiceHistoryRoute,
  AuthenticatedUnlockedOnboardingProfileRoute:
    AuthenticatedUnlockedOnboardingProfileRoute,
  AuthenticatedUnlockedOnboardingTourRoute:
    AuthenticatedUnlockedOnboardingTourRoute,
}

const AuthenticatedUnlockedRouteWithChildren =
  AuthenticatedUnlockedRoute._addFileChildren(
    AuthenticatedUnlockedRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminParametragesRoute: typeof AuthenticatedAdminParametragesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminParametragesRoute: AuthenticatedAdminParametragesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCoachRouteChildren {
  AuthenticatedCoachEntrepreneurIdRoute: typeof AuthenticatedCoachEntrepreneurIdRoute
  AuthenticatedCoachIndexRoute: typeof AuthenticatedCoachIndexRoute
}

const AuthenticatedCoachRouteChildren: AuthenticatedCoachRouteChildren = {
  AuthenticatedCoachEntrepreneurIdRoute: AuthenticatedCoachEntrepreneurIdRoute,
  AuthenticatedCoachIndexRoute: AuthenticatedCoachIndexRoute,
}

const AuthenticatedCoachRouteWithChildren =
  AuthenticatedCoachRoute._addFileChildren(AuthenticatedCoachRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedUnlockedRoute: typeof AuthenticatedUnlockedRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUnlockedRoute: AuthenticatedUnlockedRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCoachRoute: AuthenticatedCoachRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BackofficeLoginRoute: BackofficeLoginRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
